# Generated by Django 5.0.1 on 2024-02-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=50)),
                ('free', models.CharField(max_length=50)),
                ('lite', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('plus', models.CharField(max_length=50)),
            ],
        ),
    ]
